module top #(
)(
    input  wire clk,          // 50 MHz
    input  wire reset,        // Asynchronous reset (button)
    input  wire init_signal,  // Initialization signal

    // AXI Stream Interface for DMA
    output wire [255:0] axi_tdata,  // Adjusted to 256 bits
    output reg axi_tvalid,          // Data valid signal for AXI DMA
    input  wire axi_tready          // Ready signal from AXI DMA
);
    
    // Internal signals
    wire reset_sync;
    reg  reset_sync_ff1, reset_sync_ff2;  // Reset synchronizer signals
    wire reset_active_high = ~reset;      // Active-high reset signal
    wire init_signal_high = ~init_signal; // Invert init signal if necessary

    wire [5:0] spike_pos_out;
    wire spike_flg_out;
    wire signed [39:0] o_x_0;
    wire signed [39:0] o_x_1;
    wire signed [39:0] o_x_est_0;
    wire signed [39:0] o_x_est_1;
    wire signed [39:0] o_pot;
    wire done;

    // Synchronize the reset signal to the 50 MHz clock domain
    always @(posedge clk) begin
        if (reset_active_high) begin
            reset_sync_ff1 <= 1'b1;
            reset_sync_ff2 <= 1'b1;
        end else begin
            reset_sync_ff1 <= 1'b0;
            reset_sync_ff2 <= reset_sync_ff1;
        end
    end

    // Use this synchronized reset signal in the rest of the design
    assign reset_sync = reset_sync_ff2;

    // Instantiate EBN module, using the 50 MHz clock
    EBN ebn_inst (
        .clk(clk),             // 50 MHz clock generated by Clocking Wizard
        .reset(reset_sync),    // Use synchronized reset
        .init_signal(init_signal_high),
        .spike_flg_out(spike_flg_out),
        .spike_pos_out(spike_pos_out),
        .o_x_0(o_x_0),
        .o_x_1(o_x_1),
        .o_x_est_0(o_x_est_0),
        .o_x_est_1(o_x_est_1),
        .o_pot(o_pot),
        .done(done)
    );

    // Concatenate all output signals into a single 256-bit data stream, with zero padding for the extra bits
    assign axi_tdata = {spike_pos_out, spike_flg_out, o_x_0, o_x_1, o_x_est_0, o_x_est_1, o_pot, 49'b0};  // Pad with 89 zero bits

    // Data is valid when the done signal is high and AXI DMA is ready
    always @(posedge clk or posedge reset_sync) begin
        if (reset_sync) begin
            axi_tvalid <= 1'b0;    // Reset axi_tvalid
        end else begin
            // Assert axi_tvalid when data is done and AXI DMA is ready
            axi_tvalid <= (done && axi_tready);
        end
    end

endmodule