module top #(
)(
    input  logic clk100mhz,    // 100 MHz input clock
    input  logic reset,        // Asynchronous reset (button)
    input  logic init_signal,  // Initialization signal
    output logic spike_flg,  // Output potential
    output logic done          // Done signal
);
    
    logic clk;                 // 50 MHz clock generated by Clocking Wizard
    logic locked;              // Clock lock signal (optional)
    logic reset_sync, reset_sync_ff1, reset_sync_ff2;  // Reset synchronizer signals

    // Instantiate the Clocking Wizard to generate 50 MHz clock
    clk_wiz_0 clk_wizard_inst (
        .clk_in1(clk100mhz),   // 100 MHz clock input from ZedBoard
        .clk_out1(clk),        // 50 MHz clock output for EBN
        .reset(reset),         // Reset for the Clocking Wizard (direct)
        .locked(locked)        // Lock signal
    );

    // Synchronize the reset signal to the 50 MHz clock domain
    always_ff @(posedge clk) begin
        if (reset) begin
            reset_sync_ff1 <= 1'b1;
            reset_sync_ff2 <= 1'b1;
        end else begin
            reset_sync_ff1 <= 1'b0;
            reset_sync_ff2 <= reset_sync_ff1;
        end
    end

    // Use this synchronized reset signal in the rest of the design
    assign reset_sync = reset_sync_ff2;

    // Instantiate EBN module, using the 50 MHz clock
    EBN ebn_inst (
        .clk(clk),             // 50 MHz clock generated by Clocking Wizard
        .reset(reset_sync),    // Use synchronized reset
        .init_signal(init_signal),
        .spike_flg(spike_flg),
        .done(done)
    );

endmodule
