`timescale 1ns/1ns
module EBN_tb;
    parameter N                 = 64;
    parameter Dims              = 2;
    parameter NzMemb            = 40'h 68DB8;
    parameter Gain_D            = 40'h 2000000;
    parameter K                 = 40'h 20C49B;
    parameter LambdaV           = 40'h 3200000000;
    parameter Lambda            = 40'h A00000000;
    parameter dyn               = 40'h 800000000;
    parameter One               = 40'h 100000000;
    parameter Three             = 40'h 300000000;
    parameter Eta_W             = 40'h 4CCCCCCC; //learning rate
    parameter dt                = 40'h 68DB8;
    parameter learn_thresh      = 1006;
    parameter learn_flg         = 1;
    parameter INTEGER_BITS      = 8;
    parameter FRACTIONAL_BITS   = 32;
    parameter A_ROWS            = 1;
    parameter B_COLS            = 1;

    integer counter = 0, l = 0, count_done = 0, count_it = 1;
    logic                                                 clk;
    logic                                                 reset;
    logic                                                 init_signal;
    logic                                                 spike_flg_out;
    integer i = 0;
    wire [5:0] spike_pos_out;
    wire signed [INTEGER_BITS + FRACTIONAL_BITS - 1:0] o_x_0;
    wire signed [INTEGER_BITS + FRACTIONAL_BITS - 1:0] o_x_1;
    wire signed [INTEGER_BITS + FRACTIONAL_BITS - 1:0] o_x_est_0;
    wire signed [INTEGER_BITS + FRACTIONAL_BITS - 1:0] o_x_est_1;
    wire signed [INTEGER_BITS + FRACTIONAL_BITS - 1:0] o_pot;
    
    EBN #(
        .N(N),
        .Dims(Dims),
        .dyn(dyn),
        .NzMemb(NzMemb),
        .Gain_D(Gain_D),
        .K(K),
        .LambdaV(LambdaV),
        .Lambda(Lambda),
        .One(One),
        .Three(Three),
        .Eta_W(Eta_W),
        .dt(dt),
        .learn_thresh(learn_thresh),
        .learn_flg(learn_flg),
        .INTEGER_BITS(INTEGER_BITS),
        .FRACTIONAL_BITS(FRACTIONAL_BITS),
        .A_ROWS(A_ROWS),
        .B_COLS(B_COLS)
    )EBN(
        .clk(clk),             // 50 MHz clock generated by Clocking Wizard
        .reset(reset),    // Use synchronized reset
        .init_signal(init_signal),
        .spike_flg_out(spike_flg_out),
        .spike_pos_out(spike_pos_out),
        .o_x_0(o_x_0),
        .o_x_1(o_x_1),
        .o_x_est_0(o_x_est_0),
        .o_x_est_1(o_x_est_1),
        .o_pot(o_pot),
        .done(done)
    );

    always begin
        #5 clk = ~clk; 
    end

    always_ff @(posedge clk) begin
        counter <= counter + 1;
        if (EBN.done_dyn) begin
            count_done <= count_done + 1;
            $display("Completed Cycles: %0d", count_done); // Display the counter
        end
        if (EBN.Neuron.done_spike) begin
            if (l >= 15000) begin
                l <= 0;
                count_it <= count_it + 1;
                $display("Iteration Count: %0d", count_it); // Display the counter
            end
            else begin 
                l <= l + 1; 
            end
        end
    end

    initial begin
        clk = 0;
        reset = 1;            
        #20
        reset = 0;
        init_signal = 1;
        if (EBN.u_memory_manager.load_complete) begin
            init_signal = 0;
        end
    end

endmodule

    /*  file0 = $fopen("Potential_G.txt", "w");
        file1 = $fopen("Spikes_G.txt", "w");
        file2 = $fopen("Spike_Filter_G.txt", "w");
        file3 = $fopen("Desired_X_G.txt", "w");
        file4 = $fopen("Est_X_G.txt", "w");
        file5 = $fopen("Error_G.txt", "w");
        #634050225
        $fclose(file0);
        $fclose(file1);
        $fclose(file2);
        $fclose(file3);
        $fclose(file4);
        $fclose(file5);
        integer file0, file1, file2, file3, file4, file5, file6;
    */
        
        /*always_ff @(posedge clk) begin
        if (EBN.Neuron.done_lif_AU) begin
            $fwrite(file0, "%b\n", EBN.Neuron.o_pot);
        end
        if (EBN.Neuron.done_spike) begin
            for (i = 0; i < 64; i++) begin
                $fwrite(file1, "%b\n", EBN.Neuron.spike_tmp[i]);
            end
        end
        if (EBN.done_spike_f_buff) begin
            for (i = 0; i < 64; i++) begin
                $fwrite(file2, "%b\n", EBN.spike_f_data[i]);
            end
        end
        if (EBN.done_dyn) begin
            $fwrite(file3, "%b\n", EBN.Dynamic.o_x[0]);
            $fwrite(file3, "%b\n", EBN.Dynamic.o_x[1]);
        end
        if (EBN.done_dyn) begin
            $fwrite(file4, "%b\n", EBN.Dynamic.o_x_est[0]);
            $fwrite(file4, "%b\n", EBN.Dynamic.o_x_est[1]);
        end
        if (EBN.done_dyn) begin
            $fwrite(file5, "%b\n", EBN.Dynamic.o_err[0]);
            $fwrite(file5, "%b\n", EBN.Dynamic.o_err[1]);
        end
    end*/